### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by maxogden** [mafintosh/utp-native#13]
uname -a:
Linux instance-1 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3~bpo70+1 (2015-08-08) x86_64 GNU/Linux

output

```
# Pastebin GyiVKmYL
p.node)
prebuild info install We will now try to compile from source.
make: Entering directory `/usr/local/lib/node_modules/hyperpipe/node_modules/hyperdrive-archive-swarm/node_modules/hybrid-swarm/node_modules/discovery-swarm/node_modules/utp-native/build'
  CXX(target) Release/obj.target/libutp/deps/libutp/utp_internal.o
../deps/libutp/utp_internal.cpp: In member function ‘void UTPSocket::send_data(byte*, size_t, bandwidth_type_t, uint32)’:
../deps/libutp/utp_internal.cpp:752:58: error: unable to find string literal operator ‘operator"" I64u’
../deps/libutp/utp_internal.cpp: In function ‘size_t utp_process_incoming(UTPSocket*, const byte*, size_t, bool)’:
../deps/libutp/utp_internal.cpp:1783:80: error: unable to find string literal operator ‘operator"" I64u’
../deps/libutp/utp_internal.cpp:1969:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
make: *** [Release/obj.target/libutp/deps/libutp/utp_internal.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/hyperpipe/node_modules/hyperdrive-archive-swarm/node_modules/hybrid-swarm/node_modules/discovery-swarm/node_modules/utp-native/build'
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/hyperpipe/node_modules/hyperdrive-archive-swarm/node_modules/hybrid-swarm/node_modules/discovery-swarm/node_modules/utp-native/node_modules/prebuild/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:87:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:172:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/usr/local/lib/node_modules/hyperpipe/node_modules/hyperdrive-archive-swarm/node_modules/hybrid-swarm/node_modules/discovery-swarm/node_modules/utp-native/node_modules/prebuild/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:87:13)
prebuild ERR! build     at ChildProcess.emit (events.js:172:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

> sodium-prebuilt@1.0.22 install /usr/local/lib/node_modules/hyperpipe/node_modules/hypercore/node_modules/sodium-signatures/node_modules/sodium-prebuilt
> prebuild --install --preinstall make
```

**Comment by maxogden** [comment]
also maybe relevant output

prebuild WARN install /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/lib/node_modules/hyperpipe/node_modules/level/node_modules/leveldown/build/Release/leveldown.node)

**Comment by pmario** [comment]
building on windows, has the exact same problems.

**Comment by mafintosh** [comment]
fixed in latest
