### ISSUE TITLE
Uncaught Error [EINVAL]: Expected unsigned number

### ISSUE THREAD

**Issue by diasdavid** [mafintosh/utp-native#28]
I'm getting the following error when using utp-native as a dependency

```
Uncaught Error [EINVAL]: Expected unsigned number
      at Connection._connect (node_modules/utp-native/lib/connection.js:187:11)
      at UTP.connect (node_modules/utp-native/index.js:137:13)
      at Function.UTP.connect (node_modules/utp-native/index.js:45:14)
      at UTP.listener.listen (test/listen-dial.spec.js:43:33)
      at emitListening (node_modules/utp-native/index.js:248:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

I followed the port all the way down and it is always a Number.

Came to the repo to check if I could get the tests to pass and got a Error on install

```
 ⭠ master ⮀~/code/utp-native 
» npm i && npm test
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> utp-native@2.1.0 install /Users/imp/code/utp-native
> node-gyp-build

make: *** No rule to make target `Release/obj.target/libutp/deps/libutp/utp_internal.o', needed by `Release/utp.a'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/imp/code/utp-native
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! utp-native@2.1.0 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the utp-native@2.1.0 install script.
```

Looks like something changed on Node.js 10.13.0, just haven't been able to find exactly what.

**Comment by mafintosh** [comment]
Do you have a test case by any chance?

**Comment by mafintosh** [comment]
I can't reproduce. Can you share more info? :)

**Comment by mafintosh** [comment]
When building locally you have to run `npm run fetch-libutp` first. I'll add that to the docs.

**Comment by wellsmt** [comment]
Running npm run fetch-libutp worked for me!
