### ISSUE TITLE
v2.1.4 prebuilds not compatible with Electron 3

### ISSUE THREAD

**Issue by k2s** [mafintosh/utp-native#32]
When bundling Electron application with Electron builder on Window, the provided `node_modules\utp-native\prebuilds\win32-ia32\electron-napi.node` is not compatible with Electron 3.

It works if I use utp-native@2.1.3.

The error with 2.1.4 is:

```
Error: A dynamic link library (DLL) initialization routine failed.
\\?\c:\Program Files (x86)\electronapp\resources\app\node_modules\utp-native\prebuilds\win32-ia32\electron-napi.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at load (c:\Program Files (x86)\electronapp\resources\app\node_modules\node-gyp-build\index.js:19:10)
    at Object.<anonymous> (c:\Program Files (x86)\electronapp\resources\app\node_modules\utp-native\lib\binding.js:3:43)
```

**Comment by ZoeDreams** [comment]
I am having a different problem but related to utp-native@2.1.3. I am unable to install this version on mac 10.15. Some issue with a missing fetch-libutp

**Comment by mafintosh** [comment]
Should be fixed in latest I think, if not let me know
